name: worker-config

services:

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CELERY_DB_INDEX=${REDIS_CELERY_DB_INDEX}
      - REDIS_STORE_DB_INDEX=${REDIS_STORE_DB_INDEX}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - APP_BROKER_URI=${APP_BROKER_URI}
      - APP_BACKEND_URI=${APP_BACKEND_URI}
      - GCS_CREDS_PATH=${GCS_CREDS_PATH}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GC_PROJECT_ID=${GC_PROJECT_ID}
      - CELERY_APP_NAME=${CELERY_APP_NAME}
      - CELERY_APP_INCLUDE=${CELERY_APP_INCLUDE}
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_UID=${MODEL_UID}
      - PRED_PROCESSOR=${PRED_PROCESSOR}
      - DEVICE=${DEVICE}
      - SIGNED_URL_EXPIRATION_MINUTES=${SIGNED_URL_EXPIRATION_MINUTES}
      - OUTPUT_FILE_TYPE=${OUTPUT_FILE_TYPE}
      - SAVE_GEOJSON=${SAVE_GEOJSON}
      - SAVE_IMAGES=${SAVE_IMAGES}
      - SAVE_POSITIVE_IMAGES=${SAVE_POSITIVE_IMAGES}
      - SAVE_MANIFEST=${SAVE_MANIFEST}
      - PRED_MANIFEST=${PRED_MANIFEST}
      - MAKE_GIFS=${MAKE_GIFS}
      - EMBED_DATE=${EMBED_DATE}
      - FROM_LOCAL_FILES=${FROM_LOCAL_FILES}
      - BBOX_THRESHOLD=${BBOX_THRESHOLD}
      - BACKBONE_NAME=${BACKBONE_NAME}
      - NUM_CHANNELS=${NUM_CHANNELS}
      - NUM_CLASSES=${NUM_CLASSES}
      - PRETRAINED=${PRETRAINED}
      - PRETRAINED_BACKBONE=${PRETRAINED_BACKBONE}
      - TRAINABLE_LAYERS=${TRAINABLE_LAYERS}
      - PROGRESS=${PROGRESS}
      - MIN_SIZE=${MIN_SIZE}
      - MAX_SIZE=${MAX_SIZE}
      - PLANET_API_KEY=${PLANET_API_KEY}
    # depends_on:
    #   - rabbitmq
    #   - redis
    networks:
      - traefik-public
      # - bridge-net

networks:
  traefik-public:
    name: traefik_public
    external: true

  # bridge-net:
  #   name: bridge_net
  #   external: true
