name: messaging-config

services:

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    restart: always
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    ports:
      - "5672:5672"
    networks:
      - traefik-public
      # - bridge-net

  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - traefik-public
      # - bridge-net

networks:
  traefik-public:
    name: traefik_public
    external: true

  # bridge-net:
  #   name: bridge_net
  #   external: true
