name: worker-config

services:

  # rabbitmq:
  #   hostname: rabbitmq
  #   image: rabbitmq:latest
  #   restart: always
  #   volumes:
  #     - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
  #   ports:
  #     - "5672:5672"
  #   networks:
  #     - bridge-net

  # redis:
  #   hostname: redis
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - bridge-net

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CELERY_DB_INDEX=${REDIS_CELERY_DB_INDEX}
      - REDIS_STORE_DB_INDEX=${REDIS_STORE_DB_INDEX}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - APP_BROKER_URI=${APP_BROKER_URI}
      - APP_BACKEND_URI=${APP_BACKEND_URI}
      - GCS_CREDS_PATH=${GCS_CREDS_PATH}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GC_PROJECT_ID=${GC_PROJECT_ID}
      - CELERY_APP_NAME=${CELERY_APP_NAME}
      - CELERY_APP_INCLUDE=${CELERY_APP_INCLUDE}
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_UID=${MODEL_UID}
      - DEVICE=${DEVICE}
      - SIGNED_URL_EXPIRATION_MINUTES=${SIGNED_URL_EXPIRATION_MINUTES}
      - OUTPUT_FILE_TYPE=${OUTPUT_FILE_TYPE}
    # depends_on:
    #   - rabbitmq
    #   - redis
    networks:
      - bridge-net

networks:
  # bridge-net:
  #   name: bridge_net
  #   driver: bridge
  bridge-net:
    name: bridge_net  
    external: true
